def gv //global variable

pipeline {
    agent any
    stages {
        stage("init") { 
                steps {
                    script{ 
                        gv = load "script.groovy" //global 
                    }
                }
            }
        stage("build") { 
            steps {
                script{
                     gv.buildApp()
                }
            }
        }
        stage("test") {
            when{
                expression{
                    params.executeTests
                }
            }
            steps {
             script{
                     gv.testApp()
                }           
          }
        }
        stage("deploy") {
            steps {
                 script{
                     gv.deployApp()
                }
            }
        }
    }   
}
